"""CLI entry point for forensic-lab."""

import argparse
import os
import pwd
import subprocess
from pathlib import Path
from orchestrator.core.orchestrator import ForensicOrchestrator

import grp
import shutil

def _run_init(repo_root: Path) -> None:
    if not _confirm_init():
        print("[-] Aborted.")
        return

    user = pwd.getpwuid(os.getuid()).pw_name
    uid     = os.getuid()
    kvm_gid = grp.getgrnam("kvm").gr_gid


    _create_system_dirs(uid, kvm_gid)
    _create_dumps_dir(repo_root)
    _install_sudoers(user, repo_root)

    print("\n[i] Next step: python cli.py setup")


def _confirm_init() -> bool:
    print("[*] forensic-lab one-time system setup — requires sudo:")
    print("    1. Create /var/lib/forensic-lab/{disks,images}")
    print("    2. Install /etc/sudoers.d/forensic-lab")
    return input("[?] Proceed? [y/N] ").strip().lower() == "y"


def _create_system_dirs(uid: int, kvm_gid: int) -> None:
    for d in ("/var/lib/forensic-lab/disks", "/var/lib/forensic-lab/images"):
        subprocess.run(["sudo", "mkdir", "-p", d], check=True)
    subprocess.run(["sudo", "chown", "-R", f"{uid}:{kvm_gid}", "/var/lib/forensic-lab"], check=True)
    subprocess.run(["sudo", "chmod", "-R", "2775", "/var/lib/forensic-lab"], check=True)
    print("[+] System directories ready")


def _create_dumps_dir(repo_root: Path) -> None:
    d = repo_root / "shared" / "dumps"
    d.mkdir(parents=True, exist_ok=True)
    print(f"[+] Dumps directory ready: {d}")


def _install_sudoers(username: str, repo_root: Path) -> None:
    virsh_bin = shutil.which("virsh") or "/usr/bin/virsh"
    chown_bin = shutil.which("chown") or "/bin/chown"
    dumps     = repo_root / "shared" / "dumps"

    rules = [
        "# forensic-lab — generated by `python cli.py init`",
        "# Remove with: sudo rm /etc/sudoers.d/forensic-lab",
        "",
        f"{username} ALL=(ALL) NOPASSWD: {virsh_bin} dump *",
        f"{username} ALL=(ALL) NOPASSWD: {chown_bin} {username}\\:{username} /var/lib/forensic-lab/disks/*.raw",
        f"{username} ALL=(ALL) NOPASSWD: {chown_bin} {username}\\:{username} {dumps}/*.raw",
        f"{username} ALL=(ALL) NOPASSWD: {chown_bin} {username}\\:{username} {dumps}/*/*/*.raw",
        "",
    ]
    _write_sudoers("/etc/sudoers.d/forensic-lab", "\n".join(rules))


def _write_sudoers(path: str, content: str) -> None:
    result = subprocess.run(
        ["sudo", "tee", path],
        input=content, text=True, capture_output=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to write sudoers: {result.stderr}")

    check = subprocess.run(
        ["sudo", "visudo", "-c", "-f", path],
        capture_output=True, text=True,
    )
    if check.returncode != 0:
        subprocess.run(["sudo", "rm", "-f", path])
        raise RuntimeError(f"sudoers validation failed — file removed:\n{check.stderr}")

    print(f"[+] Sudoers rules installed: {path}")

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="forensic-lab")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("init", help="Initialize system directories with sudo")
    
    sub.add_parser("setup", help="Create libvirt network and pool")


    prepare = sub.add_parser("prepare", help="Prepare distro VM and baseline")
    prepare.add_argument("--distro", default="ubuntu-22.04", help="Distro ID")

    destroy = sub.add_parser("destroy", help="Destroy distro VM and storage")
    destroy.add_argument("--distro", required=True, help="Distro ID")

    pipeline = sub.add_parser(
        "pipeline",
        help="Run prepare + ISF build/export + baseline acquisition",
    )
    pipeline.add_argument("--distro", default="ubuntu-22.04", help="Distro ID")

    return parser


def main() -> None:
    repo_root = Path(__file__).resolve().parent
    args = build_parser().parse_args()

    try:
        if args.command == "init":
            _run_init(repo_root)
            return

        with ForensicOrchestrator(repo_root) as orchestrator:
            if args.command == "setup":
                orchestrator.setup()
                return

            if args.command == "prepare":
                distro_id: str = args.distro
                orchestrator.prepare(distro_id)
                return

            if args.command == "destroy":
                distro_id: str = args.distro
                orchestrator.destroy(distro_id)
                return

            if args.command == "pipeline":
                distro_id: str = args.distro
                orchestrator.setup()
                orchestrator.prepare(distro_id)
                orchestrator.build_isf(distro_id)
                manifest_path = orchestrator.acquire_baseline(distro_id)
                
                
                print(f"[+] Baseline acquisition manifest: {manifest_path}")
            
    except FileNotFoundError as e:
        print(f"[!] {e}")
        raise SystemExit(2)


if __name__ == "__main__":
    main()
