"""CLI entry point for forensic-lab."""

import argparse
import grp
import os
import pwd
import shutil
import subprocess
from pathlib import Path

from infra.provider import Provider
from orchestrator.core.config import load_config
from orchestrator.core.orchestrator import ForensicOrchestrator
from orchestrator.core.vm_manager import VMManager
from orchestrator.forensics.dumper import Dumper


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="forensic-lab")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser(
        "init",
        help="Initialize system directories with sudo + network/pool for libvirt",
    )

    prepare = sub.add_parser(
        "distro-setup",
        help="Create VM from yml profile + create ISF file + baseline snapshot",
    )
    prepare.add_argument("--distro", default="ubuntu-22.04", help="Distro ID")

    destroy = sub.add_parser("destroy", help="Destroy distro VM and storage")
    destroy.add_argument("--distro", required=True, help="Distro ID")

    run = sub.add_parser(
        "run",
        help="Run the full experiment pipeline for a given distro: create VM, run attack, dump memory, export ISF, destroy VM",
    )
    run.add_argument("--distro", default="ubuntu-22.04", help="Distro ID")

    return parser


def _confirm_init() -> bool:
    print("[*] forensic-lab one-time system setup -- requires sudo:")
    print("    1. Create /var/lib/forensic-lab/{disks,images}")
    print("    2. Install /etc/sudoers.d/forensic-lab")
    return input("[?] Proceed? [y/N] ").strip().lower() == "y"


def _create_system_dirs(uid: int, kvm_gid: int) -> None:
    for d in ("/var/lib/forensic-lab/disks", "/var/lib/forensic-lab/images"):
        subprocess.run(["sudo", "mkdir", "-p", d], check=True)
    subprocess.run(
        ["sudo", "chown", "-R", f"{uid}:{kvm_gid}", "/var/lib/forensic-lab"], check=True
    )
    subprocess.run(["sudo", "chmod", "-R", "2775", "/var/lib/forensic-lab"], check=True)
    print("[+] System directories ready")


def _create_dumps_dir(repo_root: Path) -> None:
    d = repo_root / "shared" / "dumps"
    d.mkdir(parents=True, exist_ok=True)
    print(f"[+] Dumps directory ready: {d}")


def _install_sudoers(username: str, repo_root: Path) -> None:
    virsh_bin = shutil.which("virsh") or "/usr/bin/virsh"
    rules = [
        "# forensic-lab -- generated by `python cli.py init`",
        "# Remove with: sudo rm /etc/sudoers.d/forensic-lab",
        "",
        f"{username} ALL=(ALL) NOPASSWD: {virsh_bin}",
        "",
    ]
    _write_sudoers("/etc/sudoers.d/forensic-lab", "\n".join(rules))


def _write_sudoers(path: str, content: str) -> None:
    result = subprocess.run(
        ["sudo", "tee", path],
        input=content,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to write sudoers: {result.stderr}")

    check = subprocess.run(
        ["sudo", "visudo", "-c", "-f", path],
        capture_output=True,
        text=True,
    )
    if check.returncode != 0:
        subprocess.run(["sudo", "rm", "-f", path])
        raise RuntimeError(
            f"sudoers validation failed -- file removed:\n{check.stderr}"
        )

    print(f"[+] Sudoers rules installed: {path}")


def run_init(repo_root: Path) -> None:
    if not _confirm_init():
        print("[-] Aborted.")
        return

    user = pwd.getpwuid(os.getuid()).pw_name
    uid = os.getuid()
    kvm_gid = grp.getgrnam("kvm").gr_gid

    _create_system_dirs(uid, kvm_gid)
    _create_dumps_dir(repo_root)
    _install_sudoers(user, repo_root)

    print("\n[i] Next step: python cli.py setup")


def main() -> None:
    repo_root = Path(__file__).resolve().parent
    args = build_parser().parse_args()
    cfg = load_config(repo_root)
    host_cfg = cfg["host"]
    role_defaults = cfg.get("role_defaults") or {}

    provider: Provider = Provider(
        libvirt_uri=host_cfg["libvirt_uri"],
        pool_name=host_cfg["pool_name"],
        pool_path=Path(host_cfg["pool_path"]),
    )
    vm_manager: VMManager = VMManager(
        provider=provider,
        images_path=Path(host_cfg["images_path"]),
        ssh_key=host_cfg["ssh_key"],
        ssh_pub_key=host_cfg["ssh_pub_key"],
        repo_root=repo_root,
    )
    dumper: Dumper = Dumper(repo_root)
    results_path = Path(host_cfg["shared_dir"]).expanduser() / "results"

    try:
        with ForensicOrchestrator(
            vm_manager=vm_manager,
            dumper=dumper,
            repo_root=repo_root,
            results_path=results_path,
            role_defaults=role_defaults,
        ) as orchestrator:
            if args.command == "init":
                run_init(repo_root)
                orchestrator.setup_infra()
                return

            elif args.command == "distro-setup":
                distro_id: str = args.distro
                orchestrator.prepare_lab(distro_id)
                return

            elif args.command == "run":
                distro_id: str = args.distro
                if not orchestrator.lab_exists(distro_id):
                    orchestrator.prepare_lab(distro_id)
                orchestrator.run_pipeline(distro_id)
                return

            elif args.command == "destroy":
                distro_id: str = args.distro
                orchestrator.destroy_lab(distro_id)
                # TODO: add error handling for non-existent distro/profile
                return

            else:
                print(f"[!] Unknown command: {args.command}")
                raise SystemExit(1)

    except FileNotFoundError as e:
        print(f"[!] {e}")
        raise SystemExit(2)


if __name__ == "__main__":
    main()
