"""CLI entry point for forensic-lab."""

import argparse
import grp
import os
import pwd
import shutil
import subprocess
from pathlib import Path

from infra.provider import Provider
from orchestrator.core.config import ISF_SHARED_DIR, load_config, load_profile
from orchestrator.core.orchestrator import ForensicOrchestrator
from orchestrator.core.vm_manager import VMManager
from orchestrator.forensics.dumper import Dumper
from orchestrator.forensics.vol_runner import VolatilityRunner


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="forensic-lab",
        description="Reproducible Linux attack reconstruction lab.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # init: one-time host setup (sudo required)
    sub.add_parser(
        "init",
        help="One-time host setup: system dirs, sudoers, libvirt network/pool",
    )

    # setup: prepare lab VM + build ISF + verify pipeline (idempotent)
    setup = sub.add_parser(
        "setup",
        help="Create lab VM, provision baseline, build ISF, verify pipeline (idempotent)",
    )
    setup.add_argument("--distro", default="ubuntu-22.04", help="Distro ID")

    # run: execute an experiment
    run = sub.add_parser(
        "run",
        help="Run a full experiment: revert, attack, acquire",
    )
    run.add_argument("--distro", default="ubuntu-22.04", help="Distro ID")
    run.add_argument(
        "--scenario",
        required=True,
        choices=["ptrace", "metasploit", "kernel"],
        help="Attack scenario to run",
    )

    # destroy: remove lab VM and storage
    destroy = sub.add_parser("destroy", help="Destroy lab VM and storage")
    destroy.add_argument("--distro", required=True, help="Distro ID")

    return parser


# --- init helpers --------------------------------------------------------


def _confirm_init() -> bool:
    print("[*] forensic-lab one-time host setup -- requires sudo:")
    print("  1. Create /var/lib/forensic-lab/{disks,images}")
    print("  2. Install /etc/sudoers.d/forensic-lab")
    return input("[?] Proceed? [y/N] ").strip().lower() == "y"


def _create_system_dirs(uid: int, kvm_gid: int) -> None:
    for d in ("/var/lib/forensic-lab/disks", "/var/lib/forensic-lab/images"):
        subprocess.run(["sudo", "mkdir", "-p", d], check=True)
    subprocess.run(
        ["sudo", "chown", "-R", f"{uid}:{kvm_gid}", "/var/lib/forensic-lab"],
        check=True,
    )
    subprocess.run(["sudo", "chmod", "-R", "2775", "/var/lib/forensic-lab"], check=True)
    print("[+] System directories ready")


def _setup_dumps_dir(repo_root: Path, uid: int, kvm_gid: int) -> None:
    d = repo_root / "shared" / "dumps"
    d.mkdir(parents=True, exist_ok=True)
    subprocess.run(["sudo", "chown", f"{uid}:{kvm_gid}", str(d)], check=True)
    subprocess.run(["sudo", "chmod", "2775", str(d)], check=True)


def _install_sudoers(username: str, dumps_dir: Path) -> None:
    virsh_bin = shutil.which("virsh") or "/usr/bin/virsh"
    rules = [
        "# forensic-lab -- generated by `forensic-lab init`",
        "# Remove with: sudo rm /etc/sudoers.d/forensic-lab",
        "",
        f"{username} ALL=(ALL) NOPASSWD: {virsh_bin}",
        f"{username} ALL=(ALL) NOPASSWD: /bin/chmod * {dumps_dir}/*",
        "",
    ]
    _write_sudoers("/etc/sudoers.d/forensic-lab", "\n".join(rules))


def _write_sudoers(path: str, content: str) -> None:
    result = subprocess.run(
        ["sudo", "tee", path],
        input=content,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to write sudoers: {result.stderr}")
    check = subprocess.run(
        ["sudo", "visudo", "-c", "-f", path],
        capture_output=True,
        text=True,
    )
    if check.returncode != 0:
        subprocess.run(["sudo", "rm", "-f", path])
        raise RuntimeError(
            f"sudoers validation failed -- file removed:\n{check.stderr}"
        )
    print(f"[+] Sudoers rules installed: {path}")


def run_init(repo_root: Path, host_cfg: dict) -> None:
    if not _confirm_init():
        print("[-] Aborted.")
        return
    username = pwd.getpwuid(os.getuid()).pw_name
    uid = os.getuid()
    kvm_gid = grp.getgrnam("kvm").gr_gid
    dumps_dir = Path(host_cfg["shared_dir"]).expanduser() / "dumps"
    _create_system_dirs(uid, kvm_gid)
    _setup_dumps_dir(repo_root, uid, kvm_gid)
    _install_sudoers(username, dumps_dir)
    print("\n[i] Next step: forensic-lab setup --distro ubuntu-22.04")


# --- main ----------------------------------------------------------------


def main() -> None:
    repo_root = Path(__file__).resolve().parent
    args = build_parser().parse_args()
    cfg = load_config(repo_root)
    host_cfg = cfg["host"]
    role_defaults = cfg.get("role_defaults") or {}

    provider = Provider(
        libvirt_uri=host_cfg["libvirt_uri"],
        pool_name=host_cfg["pool_name"],
        pool_path=Path(host_cfg["pool_path"]),
    )

    vm_manager = VMManager(
        provider=provider,
        images_path=Path(host_cfg["images_path"]),
        ssh_key=host_cfg["ssh_key"],
        ssh_pub_key=host_cfg["ssh_pub_key"],
        repo_root=repo_root,
    )

    dumper = Dumper(repo_root)
    results_path = Path(host_cfg["shared_dir"]).expanduser() / "results"

    # VolatilityRunner is always constructible -- only validates the binary.
    # ISF lookup happens at call time inside VolatilityRunner via distro_id.
    isf_dir = repo_root / ISF_SHARED_DIR
    vol_runner = VolatilityRunner.from_config(host_cfg, isf_dir)

    distro_id: str = getattr(args, "distro", "ubuntu-22.04")

    try:
        with ForensicOrchestrator(
            vm_manager=vm_manager,
            dumper=dumper,
            vol_runner=vol_runner,
            repo_root=repo_root,
            results_path=results_path,
            role_defaults=role_defaults,
        ) as orchestrator:

            if args.command == "init":
                run_init(repo_root, host_cfg)
                orchestrator.setup_infra()

            elif args.command == "setup":
                orchestrator.setup_infra()
                orchestrator.prepare_lab(distro_id)
                isf_path = orchestrator.build_isf(distro_id)
                print(f"[i] ISF at: {isf_path}")
                orchestrator._verify_pipeline(distro_id)
                print(f"\n[+] Setup complete for '{distro_id}'")

            elif args.command == "run":
                if not orchestrator.lab_exists(distro_id):
                    print(f"[!] Lab '{distro_id}' not found. " "Run 'setup' first.")
                    raise SystemExit(1)
                orchestrator.run_experiment(distro_id, args.scenario)

            elif args.command == "destroy":
                orchestrator.destroy_lab(distro_id)

    except FileNotFoundError as e:
        print(f"[!] {e}")
        raise SystemExit(2)


if __name__ == "__main__":
    main()
