import subprocess
from pathlib import Path
import shutil
import pwd
import os
import grp




def _confirm_init() -> bool:
    print("[*] forensic-lab one-time host setup -- requires sudo:")
    print("  1. Create /var/lib/forensic-lab/{disks,images}")
    print("  2. Install /etc/sudoers.d/forensic-lab")
    return input("[?] Proceed? [y/N] ").strip().lower() == "y"


def _create_system_dirs(uid: int, kvm_gid: int) -> None:
    for d in ("/var/lib/forensic-lab/disks", "/var/lib/forensic-lab/images"):
        subprocess.run(["sudo", "mkdir", "-p", d], check=True)
    subprocess.run(
        ["sudo", "chown", "-R", f"{uid}:{kvm_gid}", "/var/lib/forensic-lab"],
        check=True,
    )
    subprocess.run(["sudo", "chmod", "-R", "2775", "/var/lib/forensic-lab"], check=True)
    print("[+] System directories ready")


def _setup_dumps_dir(repo_root: Path, uid: int, kvm_gid: int) -> None:
    d = repo_root / "shared" / "dumps"
    d.mkdir(parents=True, exist_ok=True)
    subprocess.run(["sudo", "chown", f"{uid}:{kvm_gid}", str(d)], check=True)
    subprocess.run(["sudo", "chmod", "2775", str(d)], check=True)


def _install_sudoers(username: str, dumps_dir: Path) -> None:
    virsh_bin = shutil.which("virsh") or "/usr/bin/virsh"
    rules = [
        "# forensic-lab -- generated by `forensic-lab init`",
        "# Remove with: sudo rm /etc/sudoers.d/forensic-lab",
        "",
        f"{username} ALL=(ALL) NOPASSWD: {virsh_bin}",
        f"{username} ALL=(ALL) NOPASSWD: /bin/chown * {dumps_dir}/*",
        # f"{username} ALL=(ALL) NOPASSWD: /bin/chmod * {dumps_dir}/*",
        "",
    ]
    _write_sudoers("/etc/sudoers.d/forensic-lab", "\n".join(rules))


def _write_sudoers(path: str, content: str) -> None:
    result = subprocess.run(
        ["sudo", "tee", path],
        input=content,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to write sudoers: {result.stderr}")
    check = subprocess.run(
        ["sudo", "visudo", "-c", "-f", path],
        capture_output=True,
        text=True,
    )
    if check.returncode != 0:
        subprocess.run(["sudo", "rm", "-f", path])
        raise RuntimeError(
            f"sudoers validation failed -- file removed:\n{check.stderr}"
        )
    print(f"[+] Sudoers rules installed: {path}")


def run_init(repo_root: Path, host_cfg: dict) -> None:
    if not _confirm_init():
        print("[-] Aborted.")
        return
    username = pwd.getpwuid(os.getuid()).pw_name
    uid = os.getuid()
    kvm_gid = grp.getgrnam("kvm").gr_gid
    dumps_dir = Path(host_cfg["shared_dir"]).expanduser() / "dumps"
    _create_system_dirs(uid, kvm_gid)
    _setup_dumps_dir(repo_root, uid, kvm_gid)
    _install_sudoers(username, dumps_dir)
    print("\n[i] Next step: forensic-lab setup --distro ubuntu-22.04")

