import subprocess
from pathlib import Path
import shutil
import pwd
import os
import grp

from orchestrator.core import console
from orchestrator.core.paths import ProjectPaths


def _confirm_init(paths: ProjectPaths) -> bool:
    print("[*] forensic-lab one-time host setup -- requires sudo:")
    print(f"  1. Create {paths.state_dir}/{{disks,images}}")
    print("  2. Install /etc/sudoers.d/forensic-lab")
    return input("[?] Proceed? [y/N] ").strip().lower() == "y"


def _create_system_dirs(paths: ProjectPaths, uid: int, kvm_gid: int) -> None:
    for d in (paths.pool_dir, paths.images_dir):
        subprocess.run(["sudo", "mkdir", "-p", str(d)], check=True)
    subprocess.run(
        ["sudo", "chown", "-R", f"{uid}:{kvm_gid}", str(paths.state_dir)],
        check=True,
    )
    subprocess.run(
        ["sudo", "chmod", "-R", "2775", str(paths.state_dir)], check=True
    )
    console.ok("system directories ready")


def _setup_experiments_dir(paths: ProjectPaths, uid: int, kvm_gid: int) -> None:
    # setgid (2775) propagates the kvm group + setgid bit to the per-run
    # subdirs Python creates later, so virsh-written dumps land group-writable.
    d = paths.experiments_dir
    d.mkdir(parents=True, exist_ok=True)
    subprocess.run(["sudo", "chown", f"{uid}:{kvm_gid}", str(d)], check=True)
    subprocess.run(["sudo", "chmod", "2775", str(d)], check=True)


def _install_sudoers(username: str, images_dir: Path, experiments_dir: Path) -> None:
    virsh_bin = shutil.which("virsh") or "/usr/bin/virsh"
    chown_bin = shutil.which("chown") or "/usr/bin/chown"
    chmod_bin = shutil.which("chmod") or "/usr/bin/chmod"

    uid = os.getuid()
    gid = os.getgid()

    rules = [
        "# forensic-lab -- generated by `forensic-lab init`",
        "# Remove with: sudo rm /etc/sudoers.d/forensic-lab",
        "",
        f"{username} ALL=(ALL) NOPASSWD: {virsh_bin}",
        f"{username} ALL=(ALL) NOPASSWD: {chown_bin} {uid}\\:{gid} {experiments_dir.absolute()}/*",
        f"{username} ALL=(ALL) NOPASSWD: {chown_bin} root\\:root {images_dir.absolute()}/*",
        f"{username} ALL=(ALL) NOPASSWD: {chmod_bin} 0444 {images_dir.absolute()}/*",
        "",
    ]

    _write_sudoers("/etc/sudoers.d/forensic-lab", "\n".join(rules))


def _write_sudoers(path: str, content: str) -> None:
    result = subprocess.run(
        ["sudo", "tee", path],
        input=content,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to write sudoers: {result.stderr}")
    check = subprocess.run(
        ["sudo", "visudo", "-c", "-f", path],
        capture_output=True,
        text=True,
    )
    if check.returncode != 0:
        subprocess.run(["sudo", "rm", "-f", path])
        raise RuntimeError(
            f"sudoers validation failed -- file removed:\n{check.stderr}"
        )
    console.ok(f"sudoers rules installed: {path}")


def run_init(paths: ProjectPaths) -> None:
    if not _confirm_init(paths):
        console.err("aborted")
        return
    username = pwd.getpwuid(os.getuid()).pw_name
    uid = os.getuid()
    kvm_gid = grp.getgrnam("kvm").gr_gid

    _create_system_dirs(paths, uid, kvm_gid)
    _setup_experiments_dir(paths, uid, kvm_gid)
    _install_sudoers(username, paths.images_dir, paths.experiments_dir)
    console.info("next step: forensic-lab setup --distro ubuntu-22.04")
