- name: Install kernel debug symbols
  ansible.builtin.apt:
    name: "linux-image-{{ kernel_version }}-dbg"
    state: present

- name: Set vmlinux path
  ansible.builtin.set_fact:
    debug_vmlinux_path: "/usr/lib/debug/boot/vmlinux-{{ kernel_version }}"
